main/urls.py
from django.urls import path

from main import views

urlpatterns = [
    path('', views.index, name='index'),
]

metatoria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),
    path('about/', include('about.urls')),
    path('attractions/', include('attractions.urls')),
    path('contacts/', include('contacts.urls')),
    path('user/', include('users.urls', namespace='user'))
      
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('auth/', views.auth, name='auth'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField

class User(AbstractUser):
    image = models.ImageField(upload_to='users', blank=True, null=True, verbose_name='Avatar')
    about_me = models.TextField(blank=True, null=True, verbose_name='About Me')
    tg_contact = models.URLField(max_length=50, blank=True, null=True, verbose_name='TG')
    vk_contact = models.URLField(max_length=50, blank=True, null=True, verbose_name='VK')
    phone_number = PhoneNumberField(region="RU", blank=True, null=True, verbose_name='Phone')
    class Meta:
        db_table = 'user'
        verbose_name = 'User'
        verbose_name_plural = 'Users'
    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import RegionalPhoneNumberWidget
from users.models import User

class  UserLoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={"autofocus": True,
                                      "placeholder": "Логин"}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password",
                                          "placeholder" : "Пароль"}),
    )
    class Meta:
        model = User
        fields = ['username', 'password']

class UserRegistrationForm(UserCreationForm):

    email = forms.CharField(
        widget=forms.EmailInput(
            attrs={
                "autofocus": True,
                "placeholder" : "E-mail",
                "value": '',
            }
        )
    )

    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Имя"
            }
        )
    )

    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Логин"
            }
        )
    )
    
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "current-password",
                "placeholder" : "Пароль"
            }
        ),
    )

    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "current-password",
                "placeholder" : "Повтор пароля"
            }
        ),
    )

    class Meta:
        model = User
        fields = (
            "email",
            "first_name",
            "username",
            "password1",
            "password2",
        )

class ProfileChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "image",
            "first_name",
            "about_me",
            "tg_contact",
            "vk_contact",
            "phone_number",
        )
    
    image = forms.ImageField(
        widget=forms.FileInput(
            attrs={
                "class": "form-input",
                

            }
        ), required=False
    )

    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Имя",
                "class": "form-input",
            }
        ), required=False
    )
    about_me = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "class": "form-input",
                "placeholder": "О себе"
            }
        ), required=False
    )
    tg_contact = forms.URLField(
        widget=forms.URLInput(
            attrs={
                "class": "form-input",
                "placeholder": "Telegram"
            }
        ), required=False
    )
    vk_contact = forms.URLField(
        widget=forms.URLInput(
            attrs={
                "class": "form-input",
                "placeholder": "Вконтакте"
            }
        ), required=False
    )
    phone_number = PhoneNumberField(
        region="RU",
        widget=RegionalPhoneNumberWidget(
            attrs={
                "class": "form-input",
                "placeholder": "Телефон",
                "id": "id_phone_number",
                "default" : "",
            }
        ), required=False
    )

users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout as leave
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from users.forms import ProfileChangeForm, UserLoginForm, UserRegistrationForm
from users.models import User



def auth(request):

    login_form = UserLoginForm()
    registration_form = UserRegistrationForm()

    if request.method == 'POST':
        print(request.POST)
        if 'login' in request.POST:
            print('log')
            login_form = UserLoginForm(data=request.POST)
            if login_form.is_valid():
                username = request.POST['username']
                password = request.POST['password']
                user = authenticate(username=username, password=password)
                if user:
                    login(request, user)
                    return HttpResponseRedirect(reverse('users:profile'))
                
        elif 'password1' in request.POST:
            registration_form = UserRegistrationForm(data=request.POST)
            if registration_form.is_valid():
                registration_form.save()
                return HttpResponseRedirect(reverse('users:auth'))
    else:
        login_form = UserLoginForm()
        registration_form = UserRegistrationForm()
    context = {
        'login_form': login_form,
        'registration_form': registration_form,
    }
    return render(request, 'users/auth.html', context)

@login_required
def profile(request):
    user_info = request.user
    if request.method == 'POST':
        change_form = ProfileChangeForm(data=request.POST, instance=request.user, files=request.FILES)
        if change_form.is_valid():
            change_form.save()
            return HttpResponseRedirect(request.path)
    else:
        change_form = ProfileChangeForm(instance=request.user)
    context = {
        'change_form' : change_form,
        'user_info' : user_info,
    }
    return render(request, 'users/profile.html', context)

@login_required
def logout(request):
    leave(request)
    return HttpResponseRedirect(reverse('main:index'))

users/templates/users/auth.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VR</title>
    <link rel="stylesheet" href="{% static 'deps/css/auth_reg.css' %}">
</head>
<body>
    <header>
        <a href="{% url "main:index" %}" class="logo"><img src="{% static 'deps/img/logo.png'%}"></a>
    </header>
    <main>
        <div class="auth" id="auth">
            <h5>Войти в аккаунт</h5>
                <div class="auth_reg">
                    <span class="voiti"><b>Вход</b></span>
                    <span class="registr" id="registr">Регистрация</span>
                </div>

                <form method="post" action='{% url "users:auth" %}'>
                    {% csrf_token %}
                    
                    {% for item in login_form %}
                        {{ item }}
                    {% endfor %}

                    <span class="auth_reg">{{login_form.non_field_errors}}</span>

                    <button class='button-one' type="submit" name="login">
                        <p>Войти</p>
                        <img src="{% static 'deps/img/arrow.png'%}">
                    </button> 
                </form>
                 
        </div>
        <div class="reg" id="reg">
            <h5>Создать аккаунт</h5>
            <div class="auth_reg">
                <span class="voiti" id="voiti">Вход</span>
                <span class="registr" id="registr"><b>Регистрация</b></span>
            </div>
            <form method="post" action='{% url "users:auth" %}'>
                {% csrf_token %}
                {% for item in registration_form %}
                    {{ item }}
                {% endfor %}
                
        
                {% if registration_form %}
                    {% if registration_form.errors %}
                    
                        <script>
                            var errors = "";
                            {% for field in registration_form %}
                                {% for error in field.errors %}
                                    errors += "{{ error|escapejs }}\n";
                                {% endfor %}
                            {% endfor %}
                            
                            if (errors) {
                                alert("Ошибка Регистрации!\n\n" + errors);
                            }
                        </script>

                        {% for field in registration_form %}
                            {% for error in field.errors %}
                                <span class="auth_reg">{{ error }}</span>
                            {% endfor %}
                        {% endfor %}
                    {% endif %}
                {% endif %}

                <button class='button-one' type="submit">
                    <p>Регистрация</p>
                    <img src="{% static 'deps/img/arrow.png'%}">
                </button>
            </form>  
        </div>
    </main>
</body>
<script src="{% static 'deps/js/script.js' %}"></script>
</html>

users/templates/users/profile.html
{% extends "main/base.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'deps/css/lk.css' %}">
{% endblock %}

{% block content %}
<main>
    <div class="left">
        <div class="bio">
        
            <div class="avatar-div">
                {% if user_info.image %}
                    <img class="avatar" src="{{ user_info.image.url }}">
                {% else %}
                    <img class="avatar" src="{% static 'deps/img/empty.png' %}">
                {% endif %}
            </div>

            <div class="info_down">
                {% if user_info.first_name %}
                    <h2>{{user_info.first_name}}</h2>
                {% else %}
                    <h2>Имя</h2>
                {% endif %}
                
                    
                <div class="phone">
                    <span>Телефон</span>
                    {% if user_info.phone_number %}
                        <p>{{user_info.phone_number}}</p>
                    {% else %}
                        <p>Еще не заполнено</p>
                    {% endif %} 
                </div>

                <div class="mail">
                    <span>Email</span>
                    <p>{{user_info.email}}</p>   
                </div>

            </div>

           
            <div class="info_up">
                <form action='{% url "user:logout" %}'>
                    <button class="button-logout button-one">
                        <p>Выйти</p>
                        <img src="{% static 'deps/img/arrow.png'%}">
                    </button>
                </form>
                <button class="button-one button-change" onclick="togglePopup()">
                    <p>Редактировать</p>
                    <img src="{% static 'deps/img/arrow.png'%}">
                </button>
            </div>
        </div>
        <div class="bio_text">
            <h6>Обо мне</h6>
            {% if user_info.about_me %}
                <p class="biotext">{{user_info.about_me}}</p>
            {% else %}
                <p class="biotext">Еще не заполнено</p>
            {% endif %}
            
        </div>
    </div>
    <div class="right">
        <div class="socials">
            <p>Ссылки</p>
            <div class="vk">
                <img src="{% static 'deps/img/vk.png'%}">
                {% if user_info.vk_contact %}
                    <a href='{{user_info.vk_contact}}'>{{user_info.vk_contact}}</a>
                {% else %}
                    <p> Ещё не заполнено
                {% endif %}
            </div>

            <div class="tg">
                <img src="{% static 'deps/img/tg.png'%}">
                {% if user_info.tg_contact %}
                    <a href='{{user_info.tg_contact}}'>{{user_info.tg_contact}}</a>
                {% else %}
                    <p> Ещё не заполнено
                {% endif %}
            </div>
        </div>
    </div>
    <div id="popupOverlay" 
         class="overlay-container">
        <div class="popup-box">
            <h2 style="color: Black;">Редактор профиля</h2>
            <form class="form-container" method="post" action='{% url "users:profile" %}' enctype="multipart/form-data">
                {% csrf_token %}
                <label class="form-label">Аватар</label>
                {{change_form.image}}
                {{change_form.first_name}}
                {{change_form.about_me}}
                {{change_form.tg_contact}}
                {{change_form.vk_contact}}
                {{change_form.phone_number}}
                
                <button class="btn-submit" type="submit">Применить</button>
            </form>
            <button class="btn-close-popup" onclick="togglePopup()">Закрыть</button>
        </div>
    </div>


            
</main>
<script>
    var errors = "";
    const phoneNumberField = document.getElementById('id_phone_number');
    {% for field in change_form %}
        {% for error in field.errors %}
            errors += "{{ error|escapejs }}\n";
        {% endfor %}
    {% endfor %}
    
    if (errors) {
        phoneNumberField.value = '';
        alert("Ошибка редактирования!\n\n" + errors);
    }
    function togglePopup() {
        const overlay = document.getElementById('popupOverlay');
        overlay.classList.toggle('show');
    }
</script>
{% endblock  %}