main/urls.py
from django.urls import path

from main import views

urlpatterns = [
    path('', views.index, name='index'),
]

metatoria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),
    path('about/', include('about.urls')),
    path('attractions/', include('attractions.urls')),
    path('contacts/', include('contacts.urls')),
    path('user/', include('users.urls', namespace='user'))
      
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('auth/', views.auth, name='auth'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
]

main/models.py
from django.db import models

# Create your models here.

class News(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='New')
    date = models.DateField(auto_now=False, auto_now_add=False, verbose_name='Date')

    def __str__(self):
        return f'{self.date}. {self.name}'
    
    class Meta:
        db_table = 'New'
        verbose_name = 'New'
        verbose_name_plural = 'News'

main/views.py
from django.shortcuts import render
from main.models import News

def index(request):
    news = News.objects.order_by('-date')[:5]
    
    context = {
        'news': news
    }
    return render(request, 'main/index.html', context)

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VR</title>
    <!-- Css -->
    {% block css %}
    {% endblock %}
    <!--  -->
</head>
<body>
    <header>
        <a href="{% url 'main:index' %}" class="logo"><img src="{% static 'deps/img/logo.png'%}"></a>
        <ul class="navbar">
            <li><a href="{% url 'main:index' %}"><b>Главная</b></a></li>
            <li><a href="{% url 'about' %}">О проекте</a></li>
            <li><a href="{% url 'attractions' %}">Достопримечательности</a></li>
            <li><a href="{% url 'contacts' %}">Контакты</a></li>
        </ul>
        <div class="lksearch">
            <a href="{% url 'user:profile' %}" class="lk"><img src="{% static 'deps/img/lk.png'%}"></a>
        </div>
    </header>
    {% block content %}
    {% endblock %}
    <footer>
        <div class="footer-up">    
            <div class="left">
                <a href="{% url 'main:index' %}" class="logo"><img src="{% static 'deps/img/logo.png'%}"></a>
                <a href=""><div class="button-one">
                    <p>Связаться с нами</p>
                    <img src="{% static 'deps/img/arrow.png'%}">
                </div></a>
                <div class="social">
                    <a><img src="{% static 'deps/img/mail.png'%}"></a>
                    <a><img src="{% static 'deps/img/tg.png'%}"></a>
                </div>
            </div>
            <div class="middle">
                <ul>
                    <li><a href="{% url 'main:index' %}"><b>Главная</b></a></li>
                    <li><a href="{% url 'about' %}">О проекте</a></li>
                    <li><a href="{% url 'attractions' %}">Достопримечательности</a></li>
                    <li><a href="{% url 'contacts' %}">Контакты</a></li>
                    <li><a href="{% url 'user:profile' %}">Профиль</a></li>
                </ul>
                <ul>
                    <li>Общие сведения</li>
                    <li>Политика конфиденциальности</li>
                    <li>Поддержка</li>
                    <li>Правила сообщества</li>
                </ul>
            </div>
            <div class="right">
                <a class="search"><img src="{% static 'deps/img/search.png'%}"></a>
                <textarea placeholder="Поиск" class="searchtext" contenteditable></textarea>
            </div>
        </div>
        <div class="footer-down">
            <img src="{% static 'deps/img/line2.png'%}">
            <div class="copyright">
                <img src="{% static 'deps/img/copyright.png' %}">
                <p>2024, Ventura. Все права защищены</p>
            </div>
        </div>
    </footer>
</body>
<script src="{% static 'deps/js/script.js' %}"></script>
</html>

main/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'deps/css/style.css' %}">
{% endblock %}

{% block content %}
<main>
    <section class="one">
        <div class="hellotext">
            <div class="hello">
                <h1>Приветствуем в виртуальном музее
                    Ульяновска - Симбирска</h1>
                <a href="#two"><div class="button-one">
                    <p>Исследовать</p>
                    <img src="{% static 'deps/img/arrow.png'%}">
                </div></a>
            </div>
            <div class="readmore">
                <p>Откройте для себя уникальную историю и культурное наследие нашего города через современные технологии.</p>
                <span><a href="{% url 'about' %}">ЧИТАТЬ ДАЛЕЕ</a></span>
            </div>
        </div>
        <div class="vrimg">
            <img src="{% static 'deps/img/vr.png'%}">
        </div>
    </section>
    <section class="two" id="two">
        <div class="interakt">
            <h2>Интерактивные экскурсии по 
                знаковым местам</h2>
            <h3>Взаимодействуйте с экспонатами и делитесь впечатлениями с друзьями в уникальном цифровом пространстве</h3>
        </div>
        <div class="minicards">
            <div class="card">
                <div class="cardtext">
                    <p>Памятник Б. М. Хитрово</p>
                    <a href="{% url 'attractions' %}#2"><img src="{% static 'deps/img/arrow3.png'%}"></a>
                </div>
            </div>
            <div class="card"><a href="{% url 'attractions' %}#3"><img src="{% static 'deps/img/arrow3.png'%}"></a></div>
            <div class="card"><a href="{% url 'attractions' %}#4"><img src="{% static 'deps/img/arrow3.png'%}"></a></div>
            <div class="card"><a href="{% url 'attractions' %}#5"><img src="{% static 'deps/img/arrow3.png'%}"></a></div>
            <div class="card"><a href="{% url 'attractions' %}#6"><img src="{% static 'deps/img/arrow3.png'%}"></a></div>
        </div>
    </section>
    <section class="three">
        <div class="news">
            {% for new in news %}
                <div class="cardnews">
                    <span class="date">{{new.date.day}}.{{new.date.month}}.{{new.date.year}}</span>
                    <p class="textnews">{{new.name}}</p>
                </div>
            {% endfor %}
        </div>
        <div class="mailing">
            <h2>Узнавайте первыми и участвуйте в жизни виртуального музея</h2>
            <div><input type="text" placeholder="e-mail">
                <a href=""><div class="button-one">
                    <p>Подписаться на рассылку</p>
                    <img src="{% static 'deps/img/arrow.png'%}">
                </div></a>
            </div>
        </div>
    </section>
</main>
{% endblock  %}